class CourtCaseRunner {

	public static void main(String[] court) {

		CourtCase ref1 = new CourtCase();
		ref1.caseId = 1;
		ref1.caseTitle = "State vs Sharma";
		ref1.courtName = "Supreme Court";
		ref1.judgeName = "Justice Rao";
		ref1.caseType = "Criminal";
		ref1.isClosed = false;
		System.out.println("the case id is " + ref1.caseId);
		System.out.println("the case title is " + ref1.caseTitle);
		System.out.println("the court name is " + ref1.courtName);
		System.out.println("the judge name is " + ref1.judgeName);
		System.out.println("the case type is " + ref1.caseType);
		System.out.println("is case closed? " + ref1.isClosed);

		CourtCase ref2 = new CourtCase();
		ref2.caseId = 2;
		ref2.caseTitle = "Mehta vs State";
		ref2.courtName = "High Court Delhi";
		ref2.judgeName = "Justice Banerjee";
		ref2.caseType = "Civil";
		ref2.isClosed = true;
		System.out.println("the case id is " + ref2.caseId);
		System.out.println("the case title is " + ref2.caseTitle);
		System.out.println("the court name is " + ref2.courtName);
		System.out.println("the judge name is " + ref2.judgeName);
		System.out.println("the case type is " + ref2.caseType);
		System.out.println("is case closed? " + ref2.isClosed);

		CourtCase ref3 = new CourtCase();
		ref3.caseId = 3;
		ref3.caseTitle = "Patel vs Desai";
		ref3.courtName = "District Court Mumbai";
		ref3.judgeName = "Justice Iyer";
		ref3.caseType = "Family";
		ref3.isClosed = false;
		System.out.println("the case id is " + ref3.caseId);
		System.out.println("the case title is " + ref3.caseTitle);
		System.out.println("the court name is " + ref3.courtName);
		System.out.println("the judge name is " + ref3.judgeName);
		System.out.println("the case type is " + ref3.caseType);
		System.out.println("is case closed? " + ref3.isClosed);

		CourtCase ref4 = new CourtCase();
		ref4.caseId = 4;
		ref4.caseTitle = "Khan vs Khan";
		ref4.courtName = "Family Court Lucknow";
		ref4.judgeName = "Justice Thomas";
		ref4.caseType = "Divorce";
		ref4.isClosed = true;
		System.out.println("the case id is " + ref4.caseId);
		System.out.println("the case title is " + ref4.caseTitle);
		System.out.println("the court name is " + ref4.courtName);
		System.out.println("the judge name is " + ref4.judgeName);
		System.out.println("the case type is " + ref4.caseType);
		System.out.println("is case closed? " + ref4.isClosed);

		CourtCase ref5 = new CourtCase();
		ref5.caseId = 5;
		ref5.caseTitle = "IT Dept vs Roy";
		ref5.courtName = "Tax Court Pune";
		ref5.judgeName = "Justice Narang";
		ref5.caseType = "Tax";
		ref5.isClosed = false;
		System.out.println("the case id is " + ref5.caseId);
		System.out.println("the case title is " + ref5.caseTitle);
		System.out.println("the court name is " + ref5.courtName);
		System.out.println("the judge name is " + ref5.judgeName);
		System.out.println("the case type is " + ref5.caseType);
		System.out.println("is case closed? " + ref5.isClosed);

		CourtCase ref6 = new CourtCase();
		ref6.caseId = 6;
		ref6.caseTitle = "Green NGO vs Factory Ltd";
		ref6.courtName = "NGT";
		ref6.judgeName = "Justice Kamat";
		ref6.caseType = "Environmental";
		ref6.isClosed = true;
		System.out.println("the case id is " + ref6.caseId);
		System.out.println("the case title is " + ref6.caseTitle);
		System.out.println("the court name is " + ref6.courtName);
		System.out.println("the judge name is " + ref6.judgeName);
		System.out.println("the case type is " + ref6.caseType);
		System.out.println("is case closed? " + ref6.isClosed);

		CourtCase ref7 = new CourtCase();
		ref7.caseId = 7;
		ref7.caseTitle = "Sharma vs University";
		ref7.courtName = "High Court Punjab";
		ref7.judgeName = "Justice Malik";
		ref7.caseType = "Education";
		ref7.isClosed = false;
		System.out.println("the case id is " + ref7.caseId);
		System.out.println("the case title is " + ref7.caseTitle);
		System.out.println("the court name is " + ref7.courtName);
		System.out.println("the judge name is " + ref7.judgeName);
		System.out.println("the case type is " + ref7.caseType);
		System.out.println("is case closed? " + ref7.isClosed);

		CourtCase ref8 = new CourtCase();
		ref8.caseId = 8;
		ref8.caseTitle = "Corporate vs Union";
		ref8.courtName = "Labour Court";
		ref8.judgeName = "Justice Bhat";
		ref8.caseType = "Labour";
		ref8.isClosed = false;
		System.out.println("the case id is " + ref8.caseId);
		System.out.println("the case title is " + ref8.caseTitle);
		System.out.println("the court name is " + ref8.courtName);
		System.out.println("the judge name is " + ref8.judgeName);
		System.out.println("the case type is " + ref8.caseType);
		System.out.println("is case closed? " + ref8.isClosed);

		CourtCase ref9 = new CourtCase();
		ref9.caseId = 9;
		ref9.caseTitle = "Election Commission vs Candidate";
		ref9.courtName = "Supreme Court";
		ref9.judgeName = "Justice Prasad";
		ref9.caseType = "Election";
		ref9.isClosed = true;
		System.out.println("the case id is " + ref9.caseId);
		System.out.println("the case title is " + ref9.caseTitle);
		System.out.println("the court name is " + ref9.courtName);
		System.out.println("the judge name is " + ref9.judgeName);
		System.out.println("the case type is " + ref9.caseType);
		System.out.println("is case closed? " + ref9.isClosed);

		CourtCase ref10 = new CourtCase();
		ref10.caseId = 10;
		ref10.caseTitle = "XYZ vs ABC Pvt Ltd";
		ref10.courtName = "Consumer Court";
		ref10.judgeName = "Justice Sen";
		ref10.caseType = "Consumer";
		ref10.isClosed = true;
		System.out.println("the case id is " + ref10.caseId);
		System.out.println("the case title is " + ref10.caseTitle);
		System.out.println("the court name is " + ref10.courtName);
		System.out.println("the judge name is " + ref10.judgeName);
		System.out.println("the case type is " + ref10.caseType);
		System.out.println("is case closed? " + ref10.isClosed);
		
				CourtCase ref11 = new CourtCase();
		ref11.caseId = 11;
		ref11.caseTitle = "Builder vs Apartment Owners";
		ref11.courtName = "Consumer Court";
		ref11.judgeName = "Justice Naik";
		ref11.caseType = "Consumer";
		ref11.isClosed = false;
		System.out.println("the case id is " + ref11.caseId);
		System.out.println("the case title is " + ref11.caseTitle);
		System.out.println("the court name is " + ref11.courtName);
		System.out.println("the judge name is " + ref11.judgeName);
		System.out.println("the case type is " + ref11.caseType);
		System.out.println("is case closed? " + ref11.isClosed);

		CourtCase ref12 = new CourtCase();
		ref12.caseId = 12;
		ref12.caseTitle = "Media Group vs Activist";
		ref12.courtName = "High Court Kolkata";
		ref12.judgeName = "Justice Ghosh";
		ref12.caseType = "Defamation";
		ref12.isClosed = true;
		System.out.println("the case id is " + ref12.caseId);
		System.out.println("the case title is " + ref12.caseTitle);
		System.out.println("the court name is " + ref12.courtName);
		System.out.println("the judge name is " + ref12.judgeName);
		System.out.println("the case type is " + ref12.caseType);
		System.out.println("is case closed? " + ref12.isClosed);

		CourtCase ref13 = new CourtCase();
		ref13.caseId = 13;
		ref13.caseTitle = "Tenant vs Landlord";
		ref13.courtName = "Civil Court Hyderabad";
		ref13.judgeName = "Justice Lal";
		ref13.caseType = "Property";
		ref13.isClosed = false;
		System.out.println("the case id is " + ref13.caseId);
		System.out.println("the case title is " + ref13.caseTitle);
		System.out.println("the court name is " + ref13.courtName);
		System.out.println("the judge name is " + ref13.judgeName);
		System.out.println("the case type is " + ref13.caseType);
		System.out.println("is case closed? " + ref13.isClosed);

		CourtCase ref14 = new CourtCase();
		ref14.caseId = 14;
		ref14.caseTitle = "Govt vs Hospital";
		ref14.courtName = "Medical Tribunal";
		ref14.judgeName = "Justice Saxena";
		ref14.caseType = "Medical Negligence";
		ref14.isClosed = false;
		System.out.println("the case id is " + ref14.caseId);
		System.out.println("the case title is " + ref14.caseTitle);
		System.out.println("the court name is " + ref14.courtName);
		System.out.println("the judge name is " + ref14.judgeName);
		System.out.println("the case type is " + ref14.caseType);
		System.out.println("is case closed? " + ref14.isClosed);

		CourtCase ref15 = new CourtCase();
		ref15.caseId = 15;
		ref15.caseTitle = "Bank vs Sharma";
		ref15.courtName = "Debt Recovery Tribunal";
		ref15.judgeName = "Justice Kale";
		ref15.caseType = "Finance";
		ref15.isClosed = true;
		System.out.println("the case id is " + ref15.caseId);
		System.out.println("the case title is " + ref15.caseTitle);
		System.out.println("the court name is " + ref15.courtName);
		System.out.println("the judge name is " + ref15.judgeName);
		System.out.println("the case type is " + ref15.caseType);
		System.out.println("is case closed? " + ref15.isClosed);

		CourtCase ref16 = new CourtCase();
		ref16.caseId = 16;
		ref16.caseTitle = "College vs Student";
		ref16.courtName = "Education Tribunal";
		ref16.judgeName = "Justice Reddy";
		ref16.caseType = "Education";
		ref16.isClosed = false;
		System.out.println("the case id is " + ref16.caseId);
		System.out.println("the case title is " + ref16.caseTitle);
		System.out.println("the court name is " + ref16.courtName);
		System.out.println("the judge name is " + ref16.judgeName);
		System.out.println("the case type is " + ref16.caseType);
		System.out.println("is case closed? " + ref16.isClosed);

		CourtCase ref17 = new CourtCase();
		ref17.caseId = 17;
		ref17.caseTitle = "NGO vs State Forest Dept";
		ref17.courtName = "Green Tribunal";
		ref17.judgeName = "Justice Menon";
		ref17.caseType = "Environmental";
		ref17.isClosed = false;
		System.out.println("the case id is " + ref17.caseId);
		System.out.println("the case title is " + ref17.caseTitle);
		System.out.println("the court name is " + ref17.courtName);
		System.out.println("the judge name is " + ref17.judgeName);
		System.out.println("the case type is " + ref17.caseType);
		System.out.println("is case closed? " + ref17.isClosed);

		CourtCase ref18 = new CourtCase();
		ref18.caseId = 18;
		ref18.caseTitle = "Traffic Dept vs Citizen";
		ref18.courtName = "Traffic Court";
		ref18.judgeName = "Justice Rao";
		ref18.caseType = "Traffic Violation";
		ref18.isClosed = true;
		System.out.println("the case id is " + ref18.caseId);
		System.out.println("the case title is " + ref18.caseTitle);
		System.out.println("the court name is " + ref18.courtName);
		System.out.println("the judge name is " + ref18.judgeName);
		System.out.println("the case type is " + ref18.caseType);
		System.out.println("is case closed? " + ref18.isClosed);

		CourtCase ref19 = new CourtCase();
		ref19.caseId = 19;
		ref19.caseTitle = "Farmer vs Govt Subsidy";
		ref19.courtName = "Agriculture Court";
		ref19.judgeName = "Justice Krishnan";
		ref19.caseType = "Civil";
		ref19.isClosed = false;
		System.out.println("the case id is " + ref19.caseId);
		System.out.println("the case title is " + ref19.caseTitle);
		System.out.println("the court name is " + ref19.courtName);
		System.out.println("the judge name is " + ref19.judgeName);
		System.out.println("the case type is " + ref19.caseType);
		System.out.println("is case closed? " + ref19.isClosed);

		CourtCase ref20 = new CourtCase();
		ref20.caseId = 20;
		ref20.caseTitle = "Citizen vs Police";
		ref20.courtName = "Human Rights Court";
		ref20.judgeName = "Justice Kulkarni";
		ref20.caseType = "Rights Violation";
		ref20.isClosed = true;
		System.out.println("the case id is " + ref20.caseId);
		System.out.println("the case title is " + ref20.caseTitle);
		System.out.println("the court name is " + ref20.courtName);
		System.out.println("the judge name is " + ref20.judgeName);
		System.out.println("the case type is " + ref20.caseType);
		System.out.println("is case closed? " + ref20.isClosed);

	}
}
