class FlowersRunner {

	public static void main(String[] flower) {

		Flowers ref1 = new Flowers();
		ref1.flowerId = 1;
		ref1.name = "Rose";
		ref1.color = "Red";
		ref1.price = 10.0;
		ref1.origin = "India";
		ref1.isFragrant = true;
		System.out.println("the flower id is " + ref1.flowerId);
		System.out.println("the flower name is " + ref1.name);
		System.out.println("the color is " + ref1.color);
		System.out.println("the price is " + ref1.price);
		System.out.println("the origin is " + ref1.origin);
		System.out.println("is it fragrant? " + ref1.isFragrant);

		Flowers ref2 = new Flowers();
		ref2.flowerId = 2;
		ref2.name = "Lily";
		ref2.color = "White";
		ref2.price = 15.0;
		ref2.origin = "Netherlands";
		ref2.isFragrant = true;
		System.out.println("the flower id is " + ref2.flowerId);
		System.out.println("the flower name is " + ref2.name);
		System.out.println("the color is " + ref2.color);
		System.out.println("the price is " + ref2.price);
		System.out.println("the origin is " + ref2.origin);
		System.out.println("is it fragrant? " + ref2.isFragrant);

		Flowers ref3 = new Flowers();
		ref3.flowerId = 3;
		ref3.name = "Tulip";
		ref3.color = "Yellow";
		ref3.price = 12.0;
		ref3.origin = "Turkey";
		ref3.isFragrant = false;
		System.out.println("the flower id is " + ref3.flowerId);
		System.out.println("the flower name is " + ref3.name);
		System.out.println("the color is " + ref3.color);
		System.out.println("the price is " + ref3.price);
		System.out.println("the origin is " + ref3.origin);
		System.out.println("is it fragrant? " + ref3.isFragrant);

		Flowers ref4 = new Flowers();
		ref4.flowerId = 4;
		ref4.name = "Jasmine";
		ref4.color = "White";
		ref4.price = 5.0;
		ref4.origin = "India";
		ref4.isFragrant = true;
		System.out.println("the flower id is " + ref4.flowerId);
		System.out.println("the flower name is " + ref4.name);
		System.out.println("the color is " + ref4.color);
		System.out.println("the price is " + ref4.price);
		System.out.println("the origin is " + ref4.origin);
		System.out.println("is it fragrant? " + ref4.isFragrant);

		Flowers ref5 = new Flowers();
		ref5.flowerId = 5;
		ref5.name = "Sunflower";
		ref5.color = "Yellow";
		ref5.price = 8.0;
		ref5.origin = "USA";
		ref5.isFragrant = false;
		System.out.println("the flower id is " + ref5.flowerId);
		System.out.println("the flower name is " + ref5.name);
		System.out.println("the color is " + ref5.color);
		System.out.println("the price is " + ref5.price);
		System.out.println("the origin is " + ref5.origin);
		System.out.println("is it fragrant? " + ref5.isFragrant);

		Flowers ref6 = new Flowers();
		ref6.flowerId = 6;
		ref6.name = "Daisy";
		ref6.color = "White";
		ref6.price = 6.0;
		ref6.origin = "Europe";
		ref6.isFragrant = false;
		System.out.println("the flower id is " + ref6.flowerId);
		System.out.println("the flower name is " + ref6.name);
		System.out.println("the color is " + ref6.color);
		System.out.println("the price is " + ref6.price);
		System.out.println("the origin is " + ref6.origin);
		System.out.println("is it fragrant? " + ref6.isFragrant);

		Flowers ref7 = new Flowers();
		ref7.flowerId = 7;
		ref7.name = "Orchid";
		ref7.color = "Purple";
		ref7.price = 20.0;
		ref7.origin = "Asia";
		ref7.isFragrant = false;
		System.out.println("the flower id is " + ref7.flowerId);
		System.out.println("the flower name is " + ref7.name);
		System.out.println("the color is " + ref7.color);
		System.out.println("the price is " + ref7.price);
		System.out.println("the origin is " + ref7.origin);
		System.out.println("is it fragrant? " + ref7.isFragrant);

		Flowers ref8 = new Flowers();
		ref8.flowerId = 8;
		ref8.name = "Marigold";
		ref8.color = "Orange";
		ref8.price = 3.0;
		ref8.origin = "India";
		ref8.isFragrant = true;
		System.out.println("the flower id is " + ref8.flowerId);
		System.out.println("the flower name is " + ref8.name);
		System.out.println("the color is " + ref8.color);
		System.out.println("the price is " + ref8.price);
		System.out.println("the origin is " + ref8.origin);
		System.out.println("is it fragrant? " + ref8.isFragrant);

		Flowers ref9 = new Flowers();
		ref9.flowerId = 9;
		ref9.name = "Peony";
		ref9.color = "Pink";
		ref9.price = 18.0;
		ref9.origin = "China";
		ref9.isFragrant = true;
		System.out.println("the flower id is " + ref9.flowerId);
		System.out.println("the flower name is " + ref9.name);
		System.out.println("the color is " + ref9.color);
		System.out.println("the price is " + ref9.price);
		System.out.println("the origin is " + ref9.origin);
		System.out.println("is it fragrant? " + ref9.isFragrant);

		Flowers ref10 = new Flowers();
		ref10.flowerId = 10;
		ref10.name = "Lotus";
		ref10.color = "Pink";
		ref10.price = 7.0;
		ref10.origin = "India";
		ref10.isFragrant = true;
		System.out.println("the flower id is " + ref10.flowerId);
		System.out.println("the flower name is " + ref10.name);
		System.out.println("the color is " + ref10.color);
		System.out.println("the price is " + ref10.price);
		System.out.println("the origin is " + ref10.origin);
		System.out.println("is it fragrant? " + ref10.isFragrant);
		
				Flowers ref11 = new Flowers();
		ref11.flowerId = 11;
		ref11.name = "Carnation";
		ref11.color = "Red";
		ref11.price = 9.0;
		ref11.origin = "Spain";
		ref11.isFragrant = true;
		System.out.println("the flower id is " + ref11.flowerId);
		System.out.println("the flower name is " + ref11.name);
		System.out.println("the color is " + ref11.color);
		System.out.println("the price is " + ref11.price);
		System.out.println("the origin is " + ref11.origin);
		System.out.println("is it fragrant? " + ref11.isFragrant);

		Flowers ref12 = new Flowers();
		ref12.flowerId = 12;
		ref12.name = "Chrysanthemum";
		ref12.color = "Yellow";
		ref12.price = 11.0;
		ref12.origin = "China";
		ref12.isFragrant = true;
		System.out.println("the flower id is " + ref12.flowerId);
		System.out.println("the flower name is " + ref12.name);
		System.out.println("the color is " + ref12.color);
		System.out.println("the price is " + ref12.price);
		System.out.println("the origin is " + ref12.origin);
		System.out.println("is it fragrant? " + ref12.isFragrant);

		Flowers ref13 = new Flowers();
		ref13.flowerId = 13;
		ref13.name = "Zinnia";
		ref13.color = "Multicolor";
		ref13.price = 4.0;
		ref13.origin = "Mexico";
		ref13.isFragrant = false;
		System.out.println("the flower id is " + ref13.flowerId);
		System.out.println("the flower name is " + ref13.name);
		System.out.println("the color is " + ref13.color);
		System.out.println("the price is " + ref13.price);
		System.out.println("the origin is " + ref13.origin);
		System.out.println("is it fragrant? " + ref13.isFragrant);

		Flowers ref14 = new Flowers();
		ref14.flowerId = 14;
		ref14.name = "Hydrangea";
		ref14.color = "Blue";
		ref14.price = 14.0;
		ref14.origin = "Japan";
		ref14.isFragrant = false;
		System.out.println("the flower id is " + ref14.flowerId);
		System.out.println("the flower name is " + ref14.name);
		System.out.println("the color is " + ref14.color);
		System.out.println("the price is " + ref14.price);
		System.out.println("the origin is " + ref14.origin);
		System.out.println("is it fragrant? " + ref14.isFragrant);

		Flowers ref15 = new Flowers();
		ref15.flowerId = 15;
		ref15.name = "Petunia";
		ref15.color = "Purple";
		ref15.price = 6.0;
		ref15.origin = "South America";
		ref15.isFragrant = false;
		System.out.println("the flower id is " + ref15.flowerId);
		System.out.println("the flower name is " + ref15.name);
		System.out.println("the color is " + ref15.color);
		System.out.println("the price is " + ref15.price);
		System.out.println("the origin is " + ref15.origin);
		System.out.println("is it fragrant? " + ref15.isFragrant);

		Flowers ref16 = new Flowers();
		ref16.flowerId = 16;
		ref16.name = "Daffodil";
		ref16.color = "Yellow";
		ref16.price = 8.0;
		ref16.origin = "UK";
		ref16.isFragrant = true;
		System.out.println("the flower id is " + ref16.flowerId);
		System.out.println("the flower name is " + ref16.name);
		System.out.println("the color is " + ref16.color);
		System.out.println("the price is " + ref16.price);
		System.out.println("the origin is " + ref16.origin);
		System.out.println("is it fragrant? " + ref16.isFragrant);

		Flowers ref17 = new Flowers();
		ref17.flowerId = 17;
		ref17.name = "Hibiscus";
		ref17.color = "Red";
		ref17.price = 5.0;
		ref17.origin = "India";
		ref17.isFragrant = false;
		System.out.println("the flower id is " + ref17.flowerId);
		System.out.println("the flower name is " + ref17.name);
		System.out.println("the color is " + ref17.color);
		System.out.println("the price is " + ref17.price);
		System.out.println("the origin is " + ref17.origin);
		System.out.println("is it fragrant? " + ref17.isFragrant);

		Flowers ref18 = new Flowers();
		ref18.flowerId = 18;
		ref18.name = "Gerbera";
		ref18.color = "Pink";
		ref18.price = 7.0;
		ref18.origin = "Africa";
		ref18.isFragrant = false;
		System.out.println("the flower id is " + ref18.flowerId);
		System.out.println("the flower name is " + ref18.name);
		System.out.println("the color is " + ref18.color);
		System.out.println("the price is " + ref18.price);
		System.out.println("the origin is " + ref18.origin);
		System.out.println("is it fragrant? " + ref18.isFragrant);

		Flowers ref19 = new Flowers();
		ref19.flowerId = 19;
		ref19.name = "Anthurium";
		ref19.color = "Red";
		ref19.price = 13.0;
		ref19.origin = "Colombia";
		ref19.isFragrant = false;
		System.out.println("the flower id is " + ref19.flowerId);
		System.out.println("the flower name is " + ref19.name);
		System.out.println("the color is " + ref19.color);
		System.out.println("the price is " + ref19.price);
		System.out.println("the origin is " + ref19.origin);
		System.out.println("is it fragrant? " + ref19.isFragrant);

		Flowers ref20 = new Flowers();
		ref20.flowerId = 20;
		ref20.name = "Bluebell";
		ref20.color = "Blue";
		ref20.price = 9.5;
		ref20.origin = "UK";
		ref20.isFragrant = true;
		System.out.println("the flower id is " + ref20.flowerId);
		System.out.println("the flower name is " + ref20.name);
		System.out.println("the color is " + ref20.color);
		System.out.println("the price is " + ref20.price);
		System.out.println("the origin is " + ref20.origin);
		System.out.println("is it fragrant? " + ref20.isFragrant);
	}
}

