class HatRunner {


	public static void main(String[] hat) {

		Hat ref1 = new Hat();
		ref1.hatId = 1;
		ref1.brand = "Adidas";
		ref1.color = "Black";
		ref1.size = "M";
		ref1.type = "Baseball";
		ref1.price = 499.0;
		System.out.println("the hat id is " + ref1.hatId);
		System.out.println("the brand is " + ref1.brand);
		System.out.println("the color is " + ref1.color);
		System.out.println("the size is " + ref1.size);
		System.out.println("the type is " + ref1.type);
		System.out.println("the price is " + ref1.price);

		Hat ref2 = new Hat();
		ref2.hatId = 2;
		ref2.brand = "Nike";
		ref2.color = "White";
		ref2.size = "L";
		ref2.type = "Snapback";
		ref2.price = 599.0;
		System.out.println("the hat id is " + ref2.hatId);
		System.out.println("the brand is " + ref2.brand);
		System.out.println("the color is " + ref2.color);
		System.out.println("the size is " + ref2.size);
		System.out.println("the type is " + ref2.type);
		System.out.println("the price is " + ref2.price);

		Hat ref3 = new Hat();
		ref3.hatId = 3;
		ref3.brand = "Puma";
		ref3.color = "Blue";
		ref3.size = "S";
		ref3.type = "Bucket";
		ref3.price = 399.0;
		System.out.println("the hat id is " + ref3.hatId);
		System.out.println("the brand is " + ref3.brand);
		System.out.println("the color is " + ref3.color);
		System.out.println("the size is " + ref3.size);
		System.out.println("the type is " + ref3.type);
		System.out.println("the price is " + ref3.price);

		Hat ref4 = new Hat();
		ref4.hatId = 4;
		ref4.brand = "Reebok";
		ref4.color = "Grey";
		ref4.size = "M";
		ref4.type = "Trucker";
		ref4.price = 450.0;
		System.out.println("the hat id is " + ref4.hatId);
		System.out.println("the brand is " + ref4.brand);
		System.out.println("the color is " + ref4.color);
		System.out.println("the size is " + ref4.size);
		System.out.println("the type is " + ref4.type);
		System.out.println("the price is " + ref4.price);

		Hat ref5 = new Hat();
		ref5.hatId = 5;
		ref5.brand = "Woodland";
		ref5.color = "Olive";
		ref5.size = "L";
		ref5.type = "Military";
		ref5.price = 550.0;
		System.out.println("the hat id is " + ref5.hatId);
		System.out.println("the brand is " + ref5.brand);
		System.out.println("the color is " + ref5.color);
		System.out.println("the size is " + ref5.size);
		System.out.println("the type is " + ref5.type);
		System.out.println("the price is " + ref5.price);

		Hat ref6 = new Hat();
		ref6.hatId = 6;
		ref6.brand = "Zara";
		ref6.color = "Beige";
		ref6.size = "M";
		ref6.type = "Fedora";
		ref6.price = 699.0;
		System.out.println("the hat id is " + ref6.hatId);
		System.out.println("the brand is " + ref6.brand);
		System.out.println("the color is " + ref6.color);
		System.out.println("the size is " + ref6.size);
		System.out.println("the type is " + ref6.type);
		System.out.println("the price is " + ref6.price);

		Hat ref7 = new Hat();
		ref7.hatId = 7;
		ref7.brand = "H&M";
		ref7.color = "Brown";
		ref7.size = "S";
		ref7.type = "Boater";
		ref7.price = 480.0;
		System.out.println("the hat id is " + ref7.hatId);
		System.out.println("the brand is " + ref7.brand);
		System.out.println("the color is " + ref7.color);
		System.out.println("the size is " + ref7.size);
		System.out.println("the type is " + ref7.type);
		System.out.println("the price is " + ref7.price);

		Hat ref8 = new Hat();
		ref8.hatId = 8;
		ref8.brand = "Levi's";
		ref8.color = "Navy";
		ref8.size = "L";
		ref8.type = "Panama";
		ref8.price = 520.0;
		System.out.println("the hat id is " + ref8.hatId);
		System.out.println("the brand is " + ref8.brand);
		System.out.println("the color is " + ref8.color);
		System.out.println("the size is " + ref8.size);
		System.out.println("the type is " + ref8.type);
		System.out.println("the price is " + ref8.price);

		Hat ref9 = new Hat();
		ref9.hatId = 9;
		ref9.brand = "Allen Solly";
		ref9.color = "Red";
		ref9.size = "M";
		ref9.type = "Top Hat";
		ref9.price = 670.0;
		System.out.println("the hat id is " + ref9.hatId);
		System.out.println("the brand is " + ref9.brand);
		System.out.println("the color is " + ref9.color);
		System.out.println("the size is " + ref9.size);
		System.out.println("the type is " + ref9.type);
		System.out.println("the price is " + ref9.price);

		Hat ref10 = new Hat();
		ref10.hatId = 10;
		ref10.brand = "HRX";
		ref10.color = "Orange";
		ref10.size = "S";
		ref10.type = "Sun Hat";
		ref10.price = 430.0;
		System.out.println("the hat id is " + ref10.hatId);
		System.out.println("the brand is " + ref10.brand);
		System.out.println("the color is " + ref10.color);
		System.out.println("the size is " + ref10.size);
		System.out.println("the type is " + ref10.type);
		System.out.println("the price is " + ref10.price);
		
				Hat ref11 = new Hat();
		ref11.hatId = 11;
		ref11.brand = "Mufti";
		ref11.color = "Sky Blue";
		ref11.size = "M";
		ref11.type = "Derby";
		ref11.price = 550.0;
		System.out.println("the hat id is " + ref11.hatId);
		System.out.println("the brand is " + ref11.brand);
		System.out.println("the color is " + ref11.color);
		System.out.println("the size is " + ref11.size);
		System.out.println("the type is " + ref11.type);
		System.out.println("the price is " + ref11.price);

		Hat ref12 = new Hat();
		ref12.hatId = 12;
		ref12.brand = "Roadster";
		ref12.color = "Maroon";
		ref12.size = "L";
		ref12.type = "Boater";
		ref12.price = 600.0;
		System.out.println("the hat id is " + ref12.hatId);
		System.out.println("the brand is " + ref12.brand);
		System.out.println("the color is " + ref12.color);
		System.out.println("the size is " + ref12.size);
		System.out.println("the type is " + ref12.type);
		System.out.println("the price is " + ref12.price);

		Hat ref13 = new Hat();
		ref13.hatId = 13;
		ref13.brand = "Biba";
		ref13.color = "Pink";
		ref13.size = "S";
		ref13.type = "Beret";
		ref13.price = 499.0;
		System.out.println("the hat id is " + ref13.hatId);
		System.out.println("the brand is " + ref13.brand);
		System.out.println("the color is " + ref13.color);
		System.out.println("the size is " + ref13.size);
		System.out.println("the type is " + ref13.type);
		System.out.println("the price is " + ref13.price);

		Hat ref14 = new Hat();
		ref14.hatId = 14;
		ref14.brand = "Gap";
		ref14.color = "Charcoal";
		ref14.size = "M";
		ref14.type = "Newsboy";
		ref14.price = 575.0;
		System.out.println("the hat id is " + ref14.hatId);
		System.out.println("the brand is " + ref14.brand);
		System.out.println("the color is " + ref14.color);
		System.out.println("the size is " + ref14.size);
		System.out.println("the type is " + ref14.type);
		System.out.println("the price is " + ref14.price);

		Hat ref15 = new Hat();
		ref15.hatId = 15;
		ref15.brand = "Wrangler";
		ref15.color = "Navy Blue";
		ref15.size = "L";
		ref15.type = "Flat Cap";
		ref15.price = 625.0;
		System.out.println("the hat id is " + ref15.hatId);
		System.out.println("the brand is " + ref15.brand);
		System.out.println("the color is " + ref15.color);
		System.out.println("the size is " + ref15.size);
		System.out.println("the type is " + ref15.type);
		System.out.println("the price is " + ref15.price);

		Hat ref16 = new Hat();
		ref16.hatId = 16;
		ref16.brand = "Spykar";
		ref16.color = "Teal";
		ref16.size = "M";
		ref16.type = "Trilby";
		ref16.price = 580.0;
		System.out.println("the hat id is " + ref16.hatId);
		System.out.println("the brand is " + ref16.brand);
		System.out.println("the color is " + ref16.color);
		System.out.println("the size is " + ref16.size);
		System.out.println("the type is " + ref16.type);
		System.out.println("the price is " + ref16.price);

		Hat ref17 = new Hat();
		ref17.hatId = 17;
		ref17.brand = "Peter England";
		ref17.color = "Tan";
		ref17.size = "S";
		ref17.type = "Pork Pie";
		ref17.price = 610.0;
		System.out.println("the hat id is " + ref17.hatId);
		System.out.println("the brand is " + ref17.brand);
		System.out.println("the color is " + ref17.color);
		System.out.println("the size is " + ref17.size);
		System.out.println("the type is " + ref17.type);
		System.out.println("the price is " + ref17.price);

		Hat ref18 = new Hat();
		ref18.hatId = 18;
		ref18.brand = "Jack & Jones";
		ref18.color = "Rust";
		ref18.size = "L";
		ref18.type = "Ascot Cap";
		ref18.price = 645.0;
		System.out.println("the hat id is " + ref18.hatId);
		System.out.println("the brand is " + ref18.brand);
		System.out.println("the color is " + ref18.color);
		System.out.println("the size is " + ref18.size);
		System.out.println("the type is " + ref18.type);
		System.out.println("the price is " + ref18.price);

		Hat ref19 = new Hat();
		ref19.hatId = 19;
		ref19.brand = "UCB";
		ref19.color = "Green";
		ref19.size = "M";
		ref19.type = "Cloche";
		ref19.price = 535.0;
		System.out.println("the hat id is " + ref19.hatId);
		System.out.println("the brand is " + ref19.brand);
		System.out.println("the color is " + ref19.color);
		System.out.println("the size is " + ref19.size);
		System.out.println("the type is " + ref19.type);
		System.out.println("the price is " + ref19.price);

		Hat ref20 = new Hat();
		ref20.hatId = 20;
		ref20.brand = "Being Human";
		ref20.color = "Lavender";
		ref20.size = "S";
		ref20.type = "Cowboy";
		ref20.price = 715.0;
		System.out.println("the hat id is " + ref20.hatId);
		System.out.println("the brand is " + ref20.brand);
		System.out.println("the color is " + ref20.color);
		System.out.println("the size is " + ref20.size);
		System.out.println("the type is " + ref20.type);
		System.out.println("the price is " + ref20.price);
	}
		}
