class NetWorkRunner {


	public static void main(String[] network) {

		NetWork ref1 = new NetWork();
		ref1.networkId = 1;
		ref1.name = "JioFiber";
		ref1.type = "Broadband";
		ref1.provider = "Reliance";
		ref1.speed = 150.0;
		ref1.price = 399.0;
		System.out.println("the network id is " + ref1.networkId);
		System.out.println("the name is " + ref1.name);
		System.out.println("the type is " + ref1.type);
		System.out.println("the provider is " + ref1.provider);
		System.out.println("the speed is " + ref1.speed);
		System.out.println("the price is " + ref1.price);

		NetWork ref2 = new NetWork();
		ref2.networkId = 2;
		ref2.name = "Airtel Xstream";
		ref2.type = "Broadband";
		ref2.provider = "Airtel";
		ref2.speed = 200.0;
		ref2.price = 499.0;
		System.out.println("the network id is " + ref2.networkId);
		System.out.println("the name is " + ref2.name);
		System.out.println("the type is " + ref2.type);
		System.out.println("the provider is " + ref2.provider);
		System.out.println("the speed is " + ref2.speed);
		System.out.println("the price is " + ref2.price);

		NetWork ref3 = new NetWork();
		ref3.networkId = 3;
		ref3.name = "Vi GigaNet";
		ref3.type = "Mobile";
		ref3.provider = "Vodafone Idea";
		ref3.speed = 60.0;
		ref3.price = 249.0;
		System.out.println("the network id is " + ref3.networkId);
		System.out.println("the name is " + ref3.name);
		System.out.println("the type is " + ref3.type);
		System.out.println("the provider is " + ref3.provider);
		System.out.println("the speed is " + ref3.speed);
		System.out.println("the price is " + ref3.price);

		NetWork ref4 = new NetWork();
		ref4.networkId = 4;
		ref4.name = "BSNL FTTH";
		ref4.type = "Fiber";
		ref4.provider = "BSNL";
		ref4.speed = 100.0;
		ref4.price = 329.0;
		System.out.println("the network id is " + ref4.networkId);
		System.out.println("the name is " + ref4.name);
		System.out.println("the type is " + ref4.type);
		System.out.println("the provider is " + ref4.provider);
		System.out.println("the speed is " + ref4.speed);
		System.out.println("the price is " + ref4.price);

		NetWork ref5 = new NetWork();
		ref5.networkId = 5;
		ref5.name = "ACT Fibernet";
		ref5.type = "Broadband";
		ref5.provider = "ACT";
		ref5.speed = 300.0;
		ref5.price = 799.0;
		System.out.println("the network id is " + ref5.networkId);
		System.out.println("the name is " + ref5.name);
		System.out.println("the type is " + ref5.type);
		System.out.println("the provider is " + ref5.provider);
		System.out.println("the speed is " + ref5.speed);
		System.out.println("the price is " + ref5.price);

		NetWork ref6 = new NetWork();
		ref6.networkId = 6;
		ref6.name = "Excitel";
		ref6.type = "Fiber";
		ref6.provider = "Excitel";
		ref6.speed = 200.0;
		ref6.price = 499.0;
		System.out.println("the network id is " + ref6.networkId);
		System.out.println("the name is " + ref6.name);
		System.out.println("the type is " + ref6.type);
		System.out.println("the provider is " + ref6.provider);
		System.out.println("the speed is " + ref6.speed);
		System.out.println("the price is " + ref6.price);

		NetWork ref7 = new NetWork();
		ref7.networkId = 7;
		ref7.name = "RailWire";
		ref7.type = "Fiber";
		ref7.provider = "RailTel";
		ref7.speed = 100.0;
		ref7.price = 399.0;
		System.out.println("the network id is " + ref7.networkId);
		System.out.println("the name is " + ref7.name);
		System.out.println("the type is " + ref7.type);
		System.out.println("the provider is " + ref7.provider);
		System.out.println("the speed is " + ref7.speed);
		System.out.println("the price is " + ref7.price);

		NetWork ref8 = new NetWork();
		ref8.networkId = 8;
		ref8.name = "Hathway";
		ref8.type = "Cable";
		ref8.provider = "Hathway";
		ref8.speed = 50.0;
		ref8.price = 299.0;
		System.out.println("the network id is " + ref8.networkId);
		System.out.println("the name is " + ref8.name);
		System.out.println("the type is " + ref8.type);
		System.out.println("the provider is " + ref8.provider);
		System.out.println("the speed is " + ref8.speed);
		System.out.println("the price is " + ref8.price);

		NetWork ref9 = new NetWork();
		ref9.networkId = 9;
		ref9.name = "GTPL";
		ref9.type = "Cable";
		ref9.provider = "GTPL";
		ref9.speed = 40.0;
		ref9.price = 250.0;
		System.out.println("the network id is " + ref9.networkId);
		System.out.println("the name is " + ref9.name);
		System.out.println("the type is " + ref9.type);
		System.out.println("the provider is " + ref9.provider);
		System.out.println("the speed is " + ref9.speed);
		System.out.println("the price is " + ref9.price);

		NetWork ref10 = new NetWork();
		ref10.networkId = 10;
		ref10.name = "Tikona";
		ref10.type = "Wireless";
		ref10.provider = "Tikona";
		ref10.speed = 70.0;
		ref10.price = 350.0;
		System.out.println("the network id is " + ref10.networkId);
		System.out.println("the name is " + ref10.name);
		System.out.println("the type is " + ref10.type);
		System.out.println("the provider is " + ref10.provider);
		System.out.println("the speed is " + ref10.speed);
		System.out.println("the price is " + ref10.price);
		
				NetWork ref11 = new NetWork();
		ref11.networkId = 11;
		ref11.name = "YOU Broadband";
		ref11.type = "Cable";
		ref11.provider = "Vodafone";
		ref11.speed = 75.0;
		ref11.price = 400.0;
		System.out.println("the network id is " + ref11.networkId);
		System.out.println("the name is " + ref11.name);
		System.out.println("the type is " + ref11.type);
		System.out.println("the provider is " + ref11.provider);
		System.out.println("the speed is " + ref11.speed);
		System.out.println("the price is " + ref11.price);

		NetWork ref12 = new NetWork();
		ref12.networkId = 12;
		ref12.name = "Spectra";
		ref12.type = "Fiber";
		ref12.provider = "SpectraNet";
		ref12.speed = 300.0;
		ref12.price = 999.0;
		System.out.println("the network id is " + ref12.networkId);
		System.out.println("the name is " + ref12.name);
		System.out.println("the type is " + ref12.type);
		System.out.println("the provider is " + ref12.provider);
		System.out.println("the speed is " + ref12.speed);
		System.out.println("the price is " + ref12.price);

		NetWork ref13 = new NetWork();
		ref13.networkId = 13;
		ref13.name = "Den Broadband";
		ref13.type = "Cable";
		ref13.provider = "Den Networks";
		ref13.speed = 60.0;
		ref13.price = 320.0;
		System.out.println("the network id is " + ref13.networkId);
		System.out.println("the name is " + ref13.name);
		System.out.println("the type is " + ref13.type);
		System.out.println("the provider is " + ref13.provider);
		System.out.println("the speed is " + ref13.speed);
		System.out.println("the price is " + ref13.price);

		NetWork ref14 = new NetWork();
		ref14.networkId = 14;
		ref14.name = "D-Vois";
		ref14.type = "Fiber";
		ref14.provider = "D-Vois";
		ref14.speed = 150.0;
		ref14.price = 450.0;
		System.out.println("the network id is " + ref14.networkId);
		System.out.println("the name is " + ref14.name);
		System.out.println("the type is " + ref14.type);
		System.out.println("the provider is " + ref14.provider);
		System.out.println("the speed is " + ref14.speed);
		System.out.println("the price is " + ref14.price);

		NetWork ref15 = new NetWork();
		ref15.networkId = 15;
		ref15.name = "Netplus";
		ref15.type = "Fiber";
		ref15.provider = "Netplus";
		ref15.speed = 100.0;
		ref15.price = 399.0;
		System.out.println("the network id is " + ref15.networkId);
		System.out.println("the name is " + ref15.name);
		System.out.println("the type is " + ref15.type);
		System.out.println("the provider is " + ref15.provider);
		System.out.println("the speed is " + ref15.speed);
		System.out.println("the price is " + ref15.price);

		NetWork ref16 = new NetWork();
		ref16.networkId = 16;
		ref16.name = "Siti Broadband";
		ref16.type = "Cable";
		ref16.provider = "Siti Networks";
		ref16.speed = 50.0;
		ref16.price = 280.0;
		System.out.println("the network id is " + ref16.networkId);
		System.out.println("the name is " + ref16.name);
		System.out.println("the type is " + ref16.type);
		System.out.println("the provider is " + ref16.provider);
		System.out.println("the speed is " + ref16.speed);
		System.out.println("the price is " + ref16.price);

		NetWork ref17 = new NetWork();
		ref17.networkId = 17;
		ref17.name = "Tikona Insta";
		ref17.type = "Wireless";
		ref17.provider = "Tikona";
		ref17.speed = 40.0;
		ref17.price = 300.0;
		System.out.println("the network id is " + ref17.networkId);
		System.out.println("the name is " + ref17.name);
		System.out.println("the type is " + ref17.type);
		System.out.println("the provider is " + ref17.provider);
		System.out.println("the speed is " + ref17.speed);
		System.out.println("the price is " + ref17.price);

		NetWork ref18 = new NetWork();
		ref18.networkId = 18;
		ref18.name = "Cherrinet";
		ref18.type = "Fiber";
		ref18.provider = "Cherrinet";
		ref18.speed = 200.0;
		ref18.price = 599.0;
		System.out.println("the network id is " + ref18.networkId);
		System.out.println("the name is " + ref18.name);
		System.out.println("the type is " + ref18.type);
		System.out.println("the provider is " + ref18.provider);
		System.out.println("the speed is " + ref18.speed);
		System.out.println("the price is " + ref18.price);

		NetWork ref19 = new NetWork();
		ref19.networkId = 19;
		ref19.name = "Nextra";
		ref19.type = "Broadband";
		ref19.provider = "Nextra";
		ref19.speed = 120.0;
		ref19.price = 499.0;
		System.out.println("the network id is " + ref19.networkId);
		System.out.println("the name is " + ref19.name);
		System.out.println("the type is " + ref19.type);
		System.out.println("the provider is " + ref19.provider);
		System.out.println("the speed is " + ref19.speed);
		System.out.println("the price is " + ref19.price);

		NetWork ref20 = new NetWork();
		ref20.networkId = 20;
		ref20.name = "Alliance Broadband";
		ref20.type = "Fiber";
		ref20.provider = "Alliance";
		ref20.speed = 150.0;
		ref20.price = 550.0;
		System.out.println("the network id is " + ref20.networkId);
		System.out.println("the name is " + ref20.name);
		System.out.println("the type is " + ref20.type);
		System.out.println("the provider is " + ref20.provider);
		System.out.println("the speed is " + ref20.speed);
		System.out.println("the price is " + ref20.price);

	}
}
