class PoliticianRunner {

	public static void main(String[] politician) {

		Politician ref1 = new Politician();
		ref1.politicianId = 1;
		ref1.name = "Narendra Modi";
		ref1.party = "BJP";
		ref1.position = "Prime Minister";
		ref1.age = 73;
		ref1.popularity = 92.5;
		System.out.println("the politician id is " + ref1.politicianId);
		System.out.println("the name is " + ref1.name);
		System.out.println("the party is " + ref1.party);
		System.out.println("the position is " + ref1.position);
		System.out.println("the age is " + ref1.age);
		System.out.println("the popularity is " + ref1.popularity);

		Politician ref2 = new Politician();
		ref2.politicianId = 2;
		ref2.name = "Rahul Gandhi";
		ref2.party = "INC";
		ref2.position = "MP";
		ref2.age = 54;
		ref2.popularity = 75.2;
		System.out.println("the politician id is " + ref2.politicianId);
		System.out.println("the name is " + ref2.name);
		System.out.println("the party is " + ref2.party);
		System.out.println("the position is " + ref2.position);
		System.out.println("the age is " + ref2.age);
		System.out.println("the popularity is " + ref2.popularity);

		Politician ref3 = new Politician();
		ref3.politicianId = 3;
		ref3.name = "Amit Shah";
		ref3.party = "BJP";
		ref3.position = "Home Minister";
		ref3.age = 59;
		ref3.popularity = 89.1;
		System.out.println("the politician id is " + ref3.politicianId);
		System.out.println("the name is " + ref3.name);
		System.out.println("the party is " + ref3.party);
		System.out.println("the position is " + ref3.position);
		System.out.println("the age is " + ref3.age);
		System.out.println("the popularity is " + ref3.popularity);

		Politician ref4 = new Politician();
		ref4.politicianId = 4;
		ref4.name = "Mamata Banerjee";
		ref4.party = "TMC";
		ref4.position = "CM of West Bengal";
		ref4.age = 69;
		ref4.popularity = 78.9;
		System.out.println("the politician id is " + ref4.politicianId);
		System.out.println("the name is " + ref4.name);
		System.out.println("the party is " + ref4.party);
		System.out.println("the position is " + ref4.position);
		System.out.println("the age is " + ref4.age);
		System.out.println("the popularity is " + ref4.popularity);

		Politician ref5 = new Politician();
		ref5.politicianId = 5;
		ref5.name = "Arvind Kejriwal";
		ref5.party = "AAP";
		ref5.position = "CM of Delhi";
		ref5.age = 56;
		ref5.popularity = 83.4;
		System.out.println("the politician id is " + ref5.politicianId);
		System.out.println("the name is " + ref5.name);
		System.out.println("the party is " + ref5.party);
		System.out.println("the position is " + ref5.position);
		System.out.println("the age is " + ref5.age);
		System.out.println("the popularity is " + ref5.popularity);

		Politician ref6 = new Politician();
		ref6.politicianId = 6;
		ref6.name = "Yogi Adityanath";
		ref6.party = "BJP";
		ref6.position = "CM of UP";
		ref6.age = 52;
		ref6.popularity = 90.3;
		System.out.println("the politician id is " + ref6.politicianId);
		System.out.println("the name is " + ref6.name);
		System.out.println("the party is " + ref6.party);
		System.out.println("the position is " + ref6.position);
		System.out.println("the age is " + ref6.age);
		System.out.println("the popularity is " + ref6.popularity);

		Politician ref7 = new Politician();
		ref7.politicianId = 7;
		ref7.name = "Sharad Pawar";
		ref7.party = "NCP";
		ref7.position = "Leader";
		ref7.age = 83;
		ref7.popularity = 60.1;
		System.out.println("the politician id is " + ref7.politicianId);
		System.out.println("the name is " + ref7.name);
		System.out.println("the party is " + ref7.party);
		System.out.println("the position is " + ref7.position);
		System.out.println("the age is " + ref7.age);
		System.out.println("the popularity is " + ref7.popularity);

		Politician ref8 = new Politician();
		ref8.politicianId = 8;
		ref8.name = "Nitish Kumar";
		ref8.party = "JD(U)";
		ref8.position = "CM of Bihar";
		ref8.age = 73;
		ref8.popularity = 68.2;
		System.out.println("the politician id is " + ref8.politicianId);
		System.out.println("the name is " + ref8.name);
		System.out.println("the party is " + ref8.party);
		System.out.println("the position is " + ref8.position);
		System.out.println("the age is " + ref8.age);
		System.out.println("the popularity is " + ref8.popularity);

		Politician ref9 = new Politician();
		ref9.politicianId = 9;
		ref9.name = "Sonia Gandhi";
		ref9.party = "INC";
		ref9.position = "Former President";
		ref9.age = 77;
		ref9.popularity = 65.5;
		System.out.println("the politician id is " + ref9.politicianId);
		System.out.println("the name is " + ref9.name);
		System.out.println("the party is " + ref9.party);
		System.out.println("the position is " + ref9.position);
		System.out.println("the age is " + ref9.age);
		System.out.println("the popularity is " + ref9.popularity);

		Politician ref10 = new Politician();
		ref10.politicianId = 10;
		ref10.name = "Devendra Fadnavis";
		ref10.party = "BJP";
		ref10.position = "Deputy CM of Maharashtra";
		ref10.age = 53;
		ref10.popularity = 77.8;
		System.out.println("the politician id is " + ref10.politicianId);
		System.out.println("the name is " + ref10.name);
		System.out.println("the party is " + ref10.party);
		System.out.println("the position is " + ref10.position);
		System.out.println("the age is " + ref10.age);
		System.out.println("the popularity is " + ref10.popularity);
		
				Politician ref11 = new Politician();
		ref11.politicianId = 11;
		ref11.name = "Pinarayi Vijayan";
		ref11.party = "CPIM";
		ref11.position = "CM of Kerala";
		ref11.age = 79;
		ref11.popularity = 72.3;
		System.out.println("the politician id is " + ref11.politicianId);
		System.out.println("the name is " + ref11.name);
		System.out.println("the party is " + ref11.party);
		System.out.println("the position is " + ref11.position);
		System.out.println("the age is " + ref11.age);
		System.out.println("the popularity is " + ref11.popularity);

		Politician ref12 = new Politician();
		ref12.politicianId = 12;
		ref12.name = "MK Stalin";
		ref12.party = "DMK";
		ref12.position = "CM of Tamil Nadu";
		ref12.age = 71;
		ref12.popularity = 79.5;
		System.out.println("the politician id is " + ref12.politicianId);
		System.out.println("the name is " + ref12.name);
		System.out.println("the party is " + ref12.party);
		System.out.println("the position is " + ref12.position);
		System.out.println("the age is " + ref12.age);
		System.out.println("the popularity is " + ref12.popularity);

		Politician ref13 = new Politician();
		ref13.politicianId = 13;
		ref13.name = "Hemant Soren";
		ref13.party = "JMM";
		ref13.position = "CM of Jharkhand";
		ref13.age = 49;
		ref13.popularity = 61.2;
		System.out.println("the politician id is " + ref13.politicianId);
		System.out.println("the name is " + ref13.name);
		System.out.println("the party is " + ref13.party);
		System.out.println("the position is " + ref13.position);
		System.out.println("the age is " + ref13.age);
		System.out.println("the popularity is " + ref13.popularity);

		Politician ref14 = new Politician();
		ref14.politicianId = 14;
		ref14.name = "K. Chandrashekar Rao";
		ref14.party = "BRS";
		ref14.position = "Former CM of Telangana";
		ref14.age = 70;
		ref14.popularity = 69.9;
		System.out.println("the politician id is " + ref14.politicianId);
		System.out.println("the name is " + ref14.name);
		System.out.println("the party is " + ref14.party);
		System.out.println("the position is " + ref14.position);
		System.out.println("the age is " + ref14.age);
		System.out.println("the popularity is " + ref14.popularity);

		Politician ref15 = new Politician();
		ref15.politicianId = 15;
		ref15.name = "Bhupesh Baghel";
		ref15.party = "INC";
		ref15.position = "Former CM of Chhattisgarh";
		ref15.age = 63;
		ref15.popularity = 66.8;
		System.out.println("the politician id is " + ref15.politicianId);
		System.out.println("the name is " + ref15.name);
		System.out.println("the party is " + ref15.party);
		System.out.println("the position is " + ref15.position);
		System.out.println("the age is " + ref15.age);
		System.out.println("the popularity is " + ref15.popularity);

		Politician ref16 = new Politician();
		ref16.politicianId = 16;
		ref16.name = "Ashok Gehlot";
		ref16.party = "INC";
		ref16.position = "Former CM of Rajasthan";
		ref16.age = 73;
		ref16.popularity = 64.4;
		System.out.println("the politician id is " + ref16.politicianId);
		System.out.println("the name is " + ref16.name);
		System.out.println("the party is " + ref16.party);
		System.out.println("the position is " + ref16.position);
		System.out.println("the age is " + ref16.age);
		System.out.println("the popularity is " + ref16.popularity);

		Politician ref17 = new Politician();
		ref17.politicianId = 17;
		ref17.name = "Basavaraj Bommai";
		ref17.party = "BJP";
		ref17.position = "Former CM of Karnataka";
		ref17.age = 64;
		ref17.popularity = 63.3;
		System.out.println("the politician id is " + ref17.politicianId);
		System.out.println("the name is " + ref17.name);
		System.out.println("the party is " + ref17.party);
		System.out.println("the position is " + ref17.position);
		System.out.println("the age is " + ref17.age);
		System.out.println("the popularity is " + ref17.popularity);

		Politician ref18 = new Politician();
		ref18.politicianId = 18;
		ref18.name = "Akhilesh Yadav";
		ref18.party = "SP";
		ref18.position = "Opposition Leader";
		ref18.age = 51;
		ref18.popularity = 70.5;
		System.out.println("the politician id is " + ref18.politicianId);
		System.out.println("the name is " + ref18.name);
		System.out.println("the party is " + ref18.party);
		System.out.println("the position is " + ref18.position);
		System.out.println("the age is " + ref18.age);
		System.out.println("the popularity is " + ref18.popularity);

		Politician ref19 = new Politician();
		ref19.politicianId = 19;
		ref19.name = "Mayawati";
		ref19.party = "BSP";
		ref19.position = "Party Leader";
		ref19.age = 68;
		ref19.popularity = 58.7;
		System.out.println("the politician id is " + ref19.politicianId);
		System.out.println("the name is " + ref19.name);
		System.out.println("the party is " + ref19.party);
		System.out.println("the position is " + ref19.position);
		System.out.println("the age is " + ref19.age);
		System.out.println("the popularity is " + ref19.popularity);

		Politician ref20 = new Politician();
		ref20.politicianId = 20;
		ref20.name = "Chandrababu Naidu";
		ref20.party = "TDP";
		ref20.position = "CM of Andhra Pradesh";
		ref20.age = 74;
		ref20.popularity = 82.0;
		System.out.println("the politician id is " + ref20.politicianId);
		System.out.println("the name is " + ref20.name);
		System.out.println("the party is " + ref20.party);
		System.out.println("the position is " + ref20.position);
		System.out.println("the age is " + ref20.age);
		System.out.println("the popularity is " + ref20.popularity);

	}
}